apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
  namespace: platform-demo
spec:
  analysis:
    interval: 30s
    maxWeight: 50
    metrics:
      - interval: 1m
        name: request-success-rate
        thresholdRange:
          min: 99
      - interval: 1m
        name: request-duration
        thresholdRange:
          max: 500
    stepWeight: 10
    threshold: 5
    webhooks:
      - metadata:
          cmd: curl -fsS http://podinfo-canary.platform-demo:9898/token | grep token
          type: bash
        name: acceptance-test
        timeout: 30s
        type: pre-rollout
        url: http://flagger-loadtester.flagger-system/
      - metadata:
          cmd: >-
            hey -z 1m -q 10 -c 2 -H 'Host: podinfo.local'
            http://ingress-nginx-controller.ingress-nginx/
        name: load-test
        timeout: 5s
        url: http://flagger-loadtester.flagger-system/
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: podinfo
  progressDeadlineSeconds: 180
  provider: nginx
  service:
    port: 9898
    targetPort: 9898
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
