apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: platform-blueprint
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/kyan9400/platform-blueprint.git
